In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core import display as ICD
import seaborn as sns
import glob
import scipy
import os
pd.set_option('display.max_columns', 100)

In [2]:
# import scikit learn packages

from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import KBinsDiscretizer
from sklearn import preprocessing

In [3]:
DATA_FOLDER = './avg_data/'

### Regression matrix creation

In [4]:
def vectorize_wind(df):
    u=np.array(df.iloc[:,0])
    dir_=np.array(df.iloc[:,1])
    df.iloc[:,:2]=pd.Dataframe(np.hstack)
    return

In [5]:
os.listdir(DATA_FOLDER)

['surf_temp.txt',
 'radiometer.csv',
 'anem2.txt',
 'anem3.txt',
 'anem1.txt',
 'anem4.txt',
 'anem5.txt',
 'anem7.txt',
 'anem6.txt']

In [6]:
all_anem=glob.glob(DATA_FOLDER + "anem*")
mast_anem=all_anem[:6]
top_anem=all_anem[6]

In [7]:
only_mag=True
h=np.arange(1.5,22,4)
df_list=[]
for idx,i in enumerate(mast_anem):
    df_temp=pd.read_csv(i, sep=" ", header=None, index_col=0, names=['u','direction'])
    df_temp['h']=h[idx]
    df_list.append(df_temp)
mast_anem_df = pd.concat(df_list)
mast_anem_df.head()

                        u  direction    h
2018-11-14 00:00:00  0.66      160.0  1.5
2018-11-14 00:01:00  0.69      187.0  1.5
2018-11-14 00:02:00  0.42      133.0  1.5
2018-11-14 00:03:00  0.58      179.0  1.5
2018-11-14 00:04:00  0.49      213.0  1.5

In [8]:
rad_df = pd.read_csv(DATA_FOLDER+'radiometer.csv', sep=" ",index_col=0)
temp_df = pd.read_csv(DATA_FOLDER+'surf_temp.txt', sep=" ",index_col=0)
top_anem_df = pd.read_csv(top_anem, sep=" ",index_col=0,names=['u_top','direction_top'])

In [9]:
time_var_df = top_anem_df.merge(rad_df,how='left', left_index=True,right_index=True)
time_var_df = time_var_df.merge(temp_df,how='left', left_index=True,right_index=True)
time_var_df.head()

,u_top,direction_top,Pyranometer Upper Irradiance [W/m$^2$],Pyranometer Lower Irradiance [W/m$^2$],Pyrgeometer Upper Irradiance [W/m$^2$],Pyrgeometer Lower Irradiance [W/m$^2$],Albedo [-],Net Solar radiation [W/m$^2$],Net (total) radiation [W/m$^2$],Net Far Infrared radiation [W/m$^2$],Sky temperature [°C],Radiometer Ground temperature [°C],Sensor Ground temperature [°C],North temperature [°C],East temperature [°C],South temperature [°C],West temperature [°C]
2018-11-14 00:00:00,2.76,298.0,1.8,-2.9,369.0,364.7,-1.1,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:01:00,2.61,316.0,2.2,-0.0,371.7,365.8,0.6,2.2,8.1,5.9,11.4,10.3,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:02:00,2.83,306.0,2.4,-2.1,370.7,366.0,-0.7,4.5,9.2,4.7,11.2,10.3,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:03:00,2.24,259.0,1.6,-0.8,369.0,368.5,-0.1,2.4,3.0,0.5,10.9,10.8,10.5,13.1,11.8,11.6,10.6
2018-11-14 00:04:00,2.78,324.0,3.3,-2.6,370.0,365.9,0.1,5.9,10.0,4.1,11.1,10.3,10.5,13.1,11.8,11.6,10.6

In [10]:
tot_df=mast_anem_df.merge(time_var_df,how='left', left_index=True,right_index=True)
tot_df = tot_df.dropna(axis=0, how='any')
tot_df = tot_df.drop(columns=['Albedo [-]'])
tot_df.head()

,u,direction,h,u_top,direction_top,Pyranometer Upper Irradiance [W/m$^2$],Pyranometer Lower Irradiance [W/m$^2$],Pyrgeometer Upper Irradiance [W/m$^2$],Pyrgeometer Lower Irradiance [W/m$^2$],Net Solar radiation [W/m$^2$],Net (total) radiation [W/m$^2$],Net Far Infrared radiation [W/m$^2$],Sky temperature [°C],Radiometer Ground temperature [°C],Sensor Ground temperature [°C],North temperature [°C],East temperature [°C],South temperature [°C],West temperature [°C]
2018-11-14 00:00:00,0.66,160.0,1.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,0.91,225.0,5.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,0.57,185.0,9.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,2.64,284.0,13.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,2.98,313.0,17.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5

Here we are going to handle the albedo case if needed

In [11]:
# tot_df[tot_df['Albedo [-]']==-np.inf]
#tot_df.index[np.isinf(tot_df).any(1)]
#tot_df.columns.to_series()[np.isinf(tot_df).any()]
#plt.plot(tot_df['Albedo [-]'].drop(np.inf))
#tot_df[~tot_df.isin([np.inf, -np.inf]).any(1)]['Albedo [-]'].plot()

#### Wind speed direction decomposition

Transform absolute value and direction in vector components

In [11]:
# create columns with coordinate velocities output
tot_df['u_x']=tot_df['u']*np.cos(np.radians(tot_df['direction']))
tot_df['u_y']=tot_df['u']*np.sin(np.radians(tot_df['direction']))

In [12]:
# create columns with coordinate velocities input top mast anemometer
tot_df['u_top_x']=tot_df['u_top']*np.cos(np.radians(tot_df['direction_top']))
tot_df['u_top_y']=tot_df['u_top']*np.sin(np.radians(tot_df['direction_top']))

In [13]:
# drop the columns which are not used anymore
tot_df=tot_df.drop(columns=['u', 'u_top', 'direction', 'direction_top'])

In [14]:
tot_df.head()

,h,Pyranometer Upper Irradiance [W/m$^2$],Pyranometer Lower Irradiance [W/m$^2$],Pyrgeometer Upper Irradiance [W/m$^2$],Pyrgeometer Lower Irradiance [W/m$^2$],Net Solar radiation [W/m$^2$],Net (total) radiation [W/m$^2$],Net Far Infrared radiation [W/m$^2$],Sky temperature [°C],Radiometer Ground temperature [°C],Sensor Ground temperature [°C],North temperature [°C],East temperature [°C],South temperature [°C],West temperature [°C],u_x,u_y,u_top_x,u_top_y
2018-11-14 00:00:00,1.5,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5,-0.620197,0.225733,1.295742,-2.436935
2018-11-14 00:00:00,5.5,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5,-0.643467,-0.643467,1.295742,-2.436935
2018-11-14 00:00:00,9.5,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5,-0.567831,-0.049679,1.295742,-2.436935
2018-11-14 00:00:00,13.5,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5,0.638674,-2.561581,1.295742,-2.436935
2018-11-14 00:00:00,17.5,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5,2.032355,-2.179434,1.295742,-2.436935

### Splitting Data for random forest (decomposition in u_x and u_y)

Since any tree in the forest will only contain so many of the variables it allows one to understand among correlated variables , which are influencing the splits most heavily. It should also allow each variable to have it's say.

In [15]:
X = np.array(tot_df.drop(columns=['u_x', 'u_y']))
y = np.array(tot_df[['u_x', 'u_y']])

In [16]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)

**Discritezing the data in bins as needed using the function KBinsDiscretizer**

In [20]:
est = KBinsDiscretizer(n_bins=[10, 10], encode='ordinal', strategy='quantile').fit(y_tr)
y_trans=est.transform(y_tr)

In [21]:
# the number of trees has to be high in order to keep the result stable
rf = RandomForestClassifier(n_estimators=10000, max_depth=None, criterion='gini', random_state=0)

In [22]:
feature_names=tot_df.drop(columns=['u_x', 'u_y']).columns.values
rf.fit(X_tr, y_trans)
sorted(zip(map(lambda x: round(x, 7), rf.feature_importances_), feature_names), reverse=True)

[(0.2885013, 'h'),
 (0.0927484, 'u_top_y'),
 (0.0863321, 'u_top_x'),
 (0.0468578, 'Pyrgeometer Lower Irradiance [W/m$^2$]'),
 (0.0453696, 'Pyranometer Upper Irradiance [W/m$^2$]'),
 (0.0450048, 'Net Far Infrared radiation [W/m$^2$]'),
 (0.0448217, 'Pyranometer Lower Irradiance [W/m$^2$]'),
 (0.0447303, 'Net Solar radiation [W/m$^2$]'),
 (0.0441729, 'Net (total) radiation [W/m$^2$]'),
 (0.0417205, 'Pyrgeometer Upper Irradiance [W/m$^2$]'),
 (0.0343696, 'Radiometer Ground temperature [°C]'),
 (0.0342696, 'North temperature [°C]'),
 (0.0327794, 'East temperature [°C]'),
 (0.0311898, 'Sky temperature [°C]'),
 (0.0303534, 'South temperature [°C]'),
 (0.0293078, 'Sensor Ground temperature [°C]'),
 (0.027471, 'West temperature [°C]')]

**Discritezing the data in bins as needed using the function Label encoder function**

Using the label encoders functions. This is extremely slow as the depth of the per tree increases since encoding has around 6000 labels

In [29]:
lab_enc = preprocessing.LabelEncoder()
y_tr_x_encoded = lab_enc.fit_transform(y_tr[:,0])
y_tr_y_encoded = lab_enc.fit_transform(y_tr[:,1])

#### Feature selection with random Forest

In [ ]:
rf = RandomForestClassifier(n_estimators=10000, max_depth=2, criterion='gini', random_state=0)

In [30]:
feature_names=tot_df.drop(columns=['u_x', 'u_y']).columns.values
y_tr_encoded=np.array([y_tr_x_encoded, y_tr_y_encoded])
rf.fit(X_tr, y_tr_encoded.T)
sorted(zip(map(lambda x: round(x, 7), rf.feature_importances_), feature_names), reverse=True)

[(0.1551937, 'Pyrgeometer Upper Irradiance [W/m$^2$]'),
 (0.1545293, 'h'),
 (0.1324766, 'Pyranometer Lower Irradiance [W/m$^2$]'),
 (0.0893273, 'Sky temperature [°C]'),
 (0.0717133, 'Net Solar radiation [W/m$^2$]'),
 (0.0665966, 'Pyranometer Upper Irradiance [W/m$^2$]'),
 (0.0596548, 'Net (total) radiation [W/m$^2$]'),
 (0.0499921, 'South temperature [°C]'),
 (0.0491783, 'u_top_x'),
 (0.0474219, 'Net Far Infrared radiation [W/m$^2$]'),
 (0.033935, 'u_top_y'),
 (0.0306356, 'West temperature [°C]'),
 (0.0302937, 'East temperature [°C]'),
 (0.0290517, 'Sensor Ground temperature [°C]'),
 (0.0, 'Radiometer Ground temperature [°C]'),
 (0.0, 'Pyrgeometer Lower Irradiance [W/m$^2$]'),
 (0.0, 'North temperature [°C]')]

### Splitting Data for random forest (no decomposition in u_x and u_y)

Since any tree in the forest will only contain so many of the variables it allows one to understand among correlated variables , which are influencing the splits most heavily. It should also allow each variable to have it's say.

In [12]:
tot_df.head()

,u,direction,h,u_top,direction_top,Pyranometer Upper Irradiance [W/m$^2$],Pyranometer Lower Irradiance [W/m$^2$],Pyrgeometer Upper Irradiance [W/m$^2$],Pyrgeometer Lower Irradiance [W/m$^2$],Net Solar radiation [W/m$^2$],Net (total) radiation [W/m$^2$],Net Far Infrared radiation [W/m$^2$],Sky temperature [°C],Radiometer Ground temperature [°C],Sensor Ground temperature [°C],North temperature [°C],East temperature [°C],South temperature [°C],West temperature [°C]
2018-11-14 00:00:00,0.66,160.0,1.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,0.91,225.0,5.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,0.57,185.0,9.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,2.64,284.0,13.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5
2018-11-14 00:00:00,2.98,313.0,17.5,2.76,298.0,1.8,-2.9,369.0,364.7,4.7,9.0,4.3,10.9,10.0,10.5,13.1,11.8,11.6,10.5

In [13]:
X = np.array(tot_df.drop(columns=['u', 'direction']))
y = np.array(tot_df[['u', 'direction']])

In [14]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)

#### Feature selection with random Forest

**Important consideration on Random Forest**

Here we are splitting the data in bins in order to have a categorized/discrete output. The number of estimators has to be high since it determines the number of trees in the forest. 

Bootstrapping is by default applied: " Random Forest instead of using the entire dataset to build one single regression tree, uses the boot- strap to build numerous trees, starting from the same training dataset. Bootstrapping is a statistical resampling method, which takes a dataset with n observations and resamples it randomly with replacements, meaning that an observation can occur more than once in bootstraping samples. This produces a series of samples, of length n, to which the algorithm can fit a regression tree. This way RF can fit numerous regression trees to the same dataset; this procedure, technically referred to as bagging, reduces the variance of the method and therefore increases its accuracy"

The maximum depth of the tree can be set to `None` and the nodes will be expanded until the leaf is pure.

**Discritezing the data in bins as needed using the function KBinsDiscretizer**

In [15]:
est = KBinsDiscretizer(n_bins=[20, 18], encode='ordinal').fit(y_tr)
y_trans=est.transform(y_tr)

In [18]:
# the number of trees has to be high in order to keep the result stable
rf = RandomForestClassifier(n_estimators=10000, max_depth=None, criterion='gini', random_state=0)

In [19]:
feature_names=tot_df.drop(columns=['u', 'direction']).columns.values
rf.fit(X_tr, y_trans)
sorted(zip(map(lambda x: round(x, 7), rf.feature_importances_), feature_names), reverse=True)

[(0.2704173, 'h'),
 (0.0932594, 'u_top'),
 (0.0770755, 'direction_top'),
 (0.0500308, 'Pyranometer Lower Irradiance [W/m$^2$]'),
 (0.0489756, 'Pyranometer Upper Irradiance [W/m$^2$]'),
 (0.0486176, 'Net Solar radiation [W/m$^2$]'),
 (0.048505, 'Pyrgeometer Lower Irradiance [W/m$^2$]'),
 (0.0484274, 'Net Far Infrared radiation [W/m$^2$]'),
 (0.0482461, 'Net (total) radiation [W/m$^2$]'),
 (0.0469962, 'Pyrgeometer Upper Irradiance [W/m$^2$]'),
 (0.0361607, 'Radiometer Ground temperature [°C]'),
 (0.0357706, 'Sky temperature [°C]'),
 (0.0311481, 'East temperature [°C]'),
 (0.030757, 'North temperature [°C]'),
 (0.0291334, 'Sensor Ground temperature [°C]'),
 (0.0286277, 'West temperature [°C]'),
 (0.0278516, 'South temperature [°C]')]